"""initial schema: profiles, household_units, weight_entries, meal_logs

Revision ID: 5612438750c8
Revises: 
Create Date: 2026-08-18 14:54:11.777031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5612438750c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(), nullable=False),
    sa.Column('calibration_method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_name', name='uq_household_unit_user_name')
    )
    with op.batch_alter_table('household_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_units_user_id'), ['user_id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('computed_totals', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_id', name='uq_meal_log_user_day')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_logs_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_type', sa.String(), nullable=False),
    sa.Column('activity_level', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('target_body_fat_pct', sa.Float(), nullable=True),
    sa.Column('dietary_pattern', sa.String(), nullable=False),
    sa.Column('eating_phase', sa.String(), nullable=False),
    sa.Column('fasting_protocol', sa.String(), nullable=False),
    sa.Column('fasting_window_start_hour', sa.Float(), nullable=True),
    sa.Column('fasting_window_end_hour', sa.Float(), nullable=True),
    sa.Column('medical_flags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_weight_entry_user_date')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))

    op.drop_table('weight_entries')
    op.drop_table('profiles')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_user_id'))

    op.drop_table('meal_logs')
    with op.batch_alter_table('household_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_units_user_id'))

    op.drop_table('household_units')
    # ### end Alembic commands ###
