/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Ingredients */
        get: operations["search_ingredients_ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredient */
        get: operations["get_ingredient_ingredients__ingredient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{ingredient_id}/nutrition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingredient Nutrition
         * @description Preview-only: the same qty+unit -> grams resolution the logging
         *     engine uses (src.core.units.resolve_to_grams, honoring the user's
         *     calibrated units), without writing anything. Lets the frontend show
         *     real nutrition before a log entry is confirmed (CLAUDE.md: AI/derived
         *     estimates must be shown before being logged, never silently accepted).
         */
        get: operations["get_ingredient_nutrition_ingredients__ingredient_id__nutrition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipes */
        get: operations["get_recipes_recipes_get"];
        put?: never;
        /** Post Recipe */
        post: operations["post_recipe_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_recipes__recipe_id__get"];
        /** Put Recipe */
        put: operations["put_recipe_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe Route */
        delete: operations["delete_recipe_route_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/nutrition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe Nutrition */
        get: operations["get_recipe_nutrition_recipes__recipe_id__nutrition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/chai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Chai */
        post: operations["build_chai_beverages_build_chai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/coffee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Coffee */
        post: operations["build_coffee_beverages_build_coffee_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/lassi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Lassi */
        post: operations["build_lassi_beverages_build_lassi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/buttermilk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Buttermilk */
        post: operations["build_buttermilk_beverages_build_buttermilk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/nimbu_paani": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Nimbu Paani */
        post: operations["build_nimbu_paani_beverages_build_nimbu_paani_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/juice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Juice */
        post: operations["build_juice_beverages_build_juice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/alcohol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Alcohol */
        post: operations["build_alcohol_beverages_build_alcohol_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beverages/build/protein_shake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Protein Shake */
        post: operations["build_protein_shake_beverages_build_protein_shake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile__user_id__get"];
        /** Put Profile */
        put: operations["put_profile_profile__user_id__put"];
        post?: never;
        /** Delete Profile Route */
        delete: operations["delete_profile_route_profile__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Profile */
        post: operations["post_profile_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/{user_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_profile__user_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Units */
        get: operations["get_units_units__user_id__get"];
        put?: never;
        /** Post Unit */
        post: operations["post_unit_units__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Entry */
        post: operations["post_entry_logs__user_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/day/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day */
        get: operations["get_day_logs__user_id__day__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/day/{date}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Day Tag
         * @description Adds a free-form tag (e.g. "diwali") to a day that already has at
         *     least one entry -- e.g. History's "mark as a festival day" action.
         *     Backs src.insights.engine's festival_flex rule and History's
         *     festival-days filter, neither of which had any way to actually set a
         *     tag before this route existed.
         */
        post: operations["post_day_tag_logs__user_id__day__date__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logged Dates
         * @description Every date this user has a log for, most recent first -- backs
         *     History's infinite-scroll timeline (paging through real dates
         *     instead of guessing how far back logs exist).
         */
        get: operations["get_logged_dates_logs__user_id__dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/range/{start}/{end}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Range
         * @description All logs between start and end (both YYYY-MM-DD, inclusive) --
         *     backs History's trend charts and personal-patterns stats, which need
         *     many days at once rather than one day per request.
         */
        get: operations["get_range_logs__user_id__range__start___end__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/week/{week_ending}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Week */
        get: operations["get_week_logs__user_id__week__week_ending__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{user_id}/entries/{log_id}/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_logs__user_id__entries__log_id___index__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_insights__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlcoholRequest */
        AlcoholRequest: {
            /**
             * Type
             * @enum {string}
             */
            type: "beer" | "wine" | "whisky" | "rum" | "vodka" | "gin" | "feni" | "toddy";
            /** Volume Ml */
            volume_ml: number;
            /** Abv Pct */
            abv_pct: number;
        };
        /** Beverage */
        Beverage: {
            /** Recipe Id */
            recipe_id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Ingredients */
            ingredients?: components["schemas"]["RecipeIngredient"][];
            oil_ghee?: components["schemas"]["OilGhee"];
            /** Servings */
            servings: number;
            /**
             * Region Tag
             * @default pan_india
             * @enum {string}
             */
            region_tag: "north" | "south" | "east" | "west" | "northeast" | "pan_india" | "custom";
            /**
             * Meal Type
             * @default beverage
             * @enum {string}
             */
            meal_type: "breakfast" | "lunch" | "dinner" | "snack" | "beverage" | "dessert" | "fasting";
            /**
             * Is Fasting Safe
             * @default false
             */
            is_fasting_safe: boolean;
            /** Tags */
            tags?: string[];
            /** Created By */
            created_by: string;
            /** Notes */
            notes?: string | null;
            /**
             * Base
             * @enum {string}
             */
            base: "water" | "milk" | "tea" | "coffee" | "yogurt" | "juice" | "alcohol" | "protein_supplement" | "other";
            /**
             * Milk Type
             * @default none
             * @enum {string}
             */
            milk_type: "none" | "toned" | "full_fat" | "skim" | "a2" | "plant";
            /**
             * Milk Ml
             * @default 0
             */
            milk_ml: number;
            /**
             * Sugar G
             * @default 0
             */
            sugar_g: number;
            /** Additives */
            additives?: string[];
            /**
             * Alcohol Pct
             * @default 0
             */
            alcohol_pct: number;
            /** Volume Ml */
            volume_ml: number;
        };
        /** ButtermilkRequest */
        ButtermilkRequest: {
            /** Volume Ml */
            volume_ml: number;
            /**
             * Salted
             * @default true
             */
            salted: boolean;
            /**
             * Spiced
             * @default true
             */
            spiced: boolean;
        };
        /** CalibrateUnitRequest */
        CalibrateUnitRequest: {
            /** Unit Name */
            unit_name: string;
            /** Volume Ml */
            volume_ml: number;
            /**
             * Method
             * @enum {string}
             */
            method: "photo_reference" | "measured" | "estimated";
        };
        /** ChaiRequest */
        ChaiRequest: {
            /** Milk Ml */
            milk_ml: number;
            /**
             * Milk Type
             * @enum {string}
             */
            milk_type: "none" | "toned" | "full_fat" | "skim" | "a2" | "plant";
            /** Sugar Tsp */
            sugar_tsp: number;
            /** Size Ml */
            size_ml: number;
            /**
             * Masala
             * @default false
             */
            masala: boolean;
            /**
             * Plant Milk Kind
             * @default soy
             * @enum {string}
             */
            plant_milk_kind: "soy" | "almond" | "oat";
        };
        /** CoffeeRequest */
        CoffeeRequest: {
            /**
             * Style
             * @enum {string}
             */
            style: "filter" | "instant" | "espresso";
            /** Milk Ml */
            milk_ml: number;
            /**
             * Milk Type
             * @enum {string}
             */
            milk_type: "none" | "toned" | "full_fat" | "skim" | "a2" | "plant";
            /** Sugar Tsp */
            sugar_tsp: number;
            /**
             * Plant Milk Kind
             * @default soy
             * @enum {string}
             */
            plant_milk_kind: "soy" | "almond" | "oat";
        };
        /** DailyBreakdown */
        DailyBreakdown: {
            /** Date */
            date: string;
            totals: components["schemas"]["NutritionTotals"];
            /** Target Kcal */
            target_kcal?: number | null;
            /** Adherence Pct */
            adherence_pct?: number | null;
            /** Entry Count */
            entry_count: number;
        };
        /** EatingWindow */
        EatingWindow: {
            /** Start Hour */
            start_hour: number;
            /** End Hour */
            end_hour: number;
            /** Note */
            note?: string | null;
        };
        /** FastingWindow */
        FastingWindow: {
            /** Start Hour */
            start_hour: number;
            /** End Hour */
            end_hour: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdUnit */
        HouseholdUnit: {
            /** User Id */
            user_id: string;
            /** Unit Name */
            unit_name: string;
            /** Volume Ml */
            volume_ml: number;
            /**
             * Calibrated At
             * Format: date-time
             */
            calibrated_at: string;
            /**
             * Calibration Method
             * @enum {string}
             */
            calibration_method: "photo_reference" | "measured" | "estimated";
        };
        /** Ingredient */
        Ingredient: {
            /** Ingredient Id */
            ingredient_id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Energy Kcal Per 100G */
            energy_kcal_per_100g: number;
            /** Protein G Per 100G */
            protein_g_per_100g: number;
            /** Fat G Per 100G */
            fat_g_per_100g: number;
            /** Carbs G Per 100G */
            carbs_g_per_100g: number;
            /** Fiber G Per 100G */
            fiber_g_per_100g: number;
            /**
             * Source
             * @enum {string}
             */
            source: "IFCT" | "USDA" | "MANUAL";
            /**
             * Category
             * @enum {string}
             */
            category: "grain" | "dal" | "vegetable" | "fruit" | "dairy" | "meat" | "fish" | "egg" | "oil_fat" | "spice" | "nut_seed" | "sweetener" | "beverage_base" | "prepared" | "other";
            /** Per Piece G */
            per_piece_g?: number | null;
        };
        /** Insight */
        Insight: {
            /** Insight Id */
            insight_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "swap" | "warning" | "celebration" | "nudge" | "hydration" | "fasting_reminder" | "festival_flex";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "suggest" | "warn" | "urgent";
            /** Title */
            title: string;
            /** Body En */
            body_en: string;
            /** Body Hi */
            body_hi: string;
            /** Body Kn */
            body_kn: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Suggested Actions */
            suggested_actions?: string[];
        };
        /** JuiceRequest */
        JuiceRequest: {
            /** Fruit */
            fruit: string;
            /** Volume Ml */
            volume_ml: number;
            /**
             * Added Sugar G
             * @default 0
             */
            added_sugar_g: number;
        };
        /** LassiRequest */
        LassiRequest: {
            /**
             * Type
             * @enum {string}
             */
            type: "sweet" | "salty" | "mango";
            /** Yogurt Ml */
            yogurt_ml: number;
            /** Sugar G */
            sugar_g: number;
            /**
             * Fruit G
             * @default 0
             */
            fruit_g: number;
        };
        /** LogEntry */
        LogEntry: {
            /** Recipe Id */
            recipe_id?: string | null;
            /** Ingredient Id */
            ingredient_id?: string | null;
            /** Qty */
            qty: number;
            /** Unit */
            unit: string;
            /** Timestamp */
            timestamp?: string | null;
            /**
             * Outside Eating Window
             * @default false
             */
            outside_eating_window: boolean;
        };
        /** MealLog */
        MealLog: {
            /** Log Id */
            log_id: string;
            /** User Id */
            user_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            computed_totals: components["schemas"]["NutritionTotals"];
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** NimbuPaaniRequest */
        NimbuPaaniRequest: {
            /** Volume Ml */
            volume_ml: number;
            /** Sugar G */
            sugar_g: number;
            /**
             * Salt
             * @default true
             */
            salt: boolean;
        };
        /** NutritionTotals */
        NutritionTotals: {
            /** Energy Kcal */
            energy_kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /** OilGhee */
        OilGhee: {
            /**
             * Type
             * @default none
             * @enum {string}
             */
            type: "oil" | "ghee" | "butter" | "none";
            /**
             * Qty G
             * @default 0
             */
            qty_g: number;
        };
        /** PlanRecommendation */
        PlanRecommendation: {
            /** Daily Kcal */
            daily_kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fiber G Min */
            fiber_g_min: number;
            /** Water Ml Min */
            water_ml_min: number;
            eating_window: components["schemas"]["EatingWindow"];
            /** Warnings */
            warnings?: components["schemas"]["PlanWarning"][];
            /** Guidance Notes */
            guidance_notes?: string[];
        };
        /** PlanWarning */
        PlanWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ProteinShakeRequest */
        ProteinShakeRequest: {
            /** Protein G */
            protein_g: number;
            /** Milk Ml */
            milk_ml: number;
            /**
             * Milk Type
             * @enum {string}
             */
            milk_type: "none" | "toned" | "full_fat" | "skim" | "a2" | "plant";
            /**
             * Banana G
             * @default 0
             */
            banana_g: number;
            /**
             * Peanut Butter G
             * @default 0
             */
            peanut_butter_g: number;
            /**
             * Protein Source
             * @default whey_isolate
             * @enum {string}
             */
            protein_source: "whey_isolate" | "whey_concentrate" | "casein";
            /**
             * Plant Milk Kind
             * @default soy
             * @enum {string}
             */
            plant_milk_kind: "soy" | "almond" | "oat";
        };
        /**
         * QuarantinedLog
         * @description What a corrupted-on-disk log file loads into instead of crashing.
         */
        QuarantinedLog: {
            /** Path */
            path: string;
            /** Raw Content */
            raw_content: string;
            /** Error */
            error: string;
            /**
             * Quarantined At
             * Format: date-time
             */
            quarantined_at: string;
        };
        /** Recipe */
        Recipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Ingredients */
            ingredients?: components["schemas"]["RecipeIngredient"][];
            oil_ghee?: components["schemas"]["OilGhee"];
            /** Servings */
            servings: number;
            /**
             * Region Tag
             * @enum {string}
             */
            region_tag: "north" | "south" | "east" | "west" | "northeast" | "pan_india" | "custom";
            /**
             * Meal Type
             * @enum {string}
             */
            meal_type: "breakfast" | "lunch" | "dinner" | "snack" | "beverage" | "dessert" | "fasting";
            /**
             * Is Fasting Safe
             * @default false
             */
            is_fasting_safe: boolean;
            /** Tags */
            tags?: string[];
            /** Created By */
            created_by: string;
            /** Notes */
            notes?: string | null;
        };
        /** RecipeIngredient */
        RecipeIngredient: {
            /** Ingredient Id */
            ingredient_id: string;
            /** Qty */
            qty: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "g" | "ml" | "katori" | "small_katori" | "glass" | "large_glass" | "tsp" | "tbsp" | "mutthi" | "plate" | "piece" | "custom";
        };
        /** TagDayRequest */
        TagDayRequest: {
            /** Tag */
            tag: string;
        };
        /** UserProfile */
        UserProfile: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /**
             * Sex
             * @enum {string}
             */
            sex: "male" | "female";
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /**
             * Body Type
             * @enum {string}
             */
            body_type: "ectomorph" | "mesomorph" | "endomorph" | "mixed";
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "sedentary" | "light" | "moderate" | "active" | "very_active";
            /**
             * Goal
             * @enum {string}
             */
            goal: "cut" | "maintain" | "lean_bulk" | "recomp";
            /** Target Body Fat Pct */
            target_body_fat_pct?: number | null;
            /**
             * Dietary Pattern
             * @enum {string}
             */
            dietary_pattern: "vegetarian" | "vegan" | "eggetarian" | "non_vegetarian" | "jain" | "satvik" | "custom";
            /**
             * Eating Phase
             * @enum {string}
             */
            eating_phase: "maintenance" | "cutting" | "lean_bulk" | "recomp" | "reverse_diet" | "refeed";
            /**
             * Fasting Protocol
             * @default none
             * @enum {string}
             */
            fasting_protocol: "none" | "16_8" | "18_6" | "20_4" | "omad" | "5_2" | "alternate_day" | "ramadan" | "ekadashi" | "navratri" | "custom";
            fasting_window?: components["schemas"]["FastingWindow"] | null;
            /** Medical Flags */
            medical_flags?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklySummary */
        WeeklySummary: {
            /** User Id */
            user_id: string;
            /** Week Start Date */
            week_start_date: string;
            /** Week End Date */
            week_end_date: string;
            /** Days */
            days: components["schemas"]["DailyBreakdown"][];
            averages: components["schemas"]["NutritionTotals"];
            /** Target Adherence Pct */
            target_adherence_pct: number;
            /** Streak Days */
            streak_days: number;
            /** Notable Days */
            notable_days?: string[];
            /** Warnings */
            warnings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_ingredients_ingredients_get: {
        parameters: {
            query?: {
                /** @description Substring match against name/aliases */
                query?: string | null;
                category?: ("grain" | "dal" | "vegetable" | "fruit" | "dairy" | "meat" | "fish" | "egg" | "oil_fat" | "spice" | "nut_seed" | "sweetener" | "beverage_base" | "prepared" | "other") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredient_ingredients__ingredient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredient_nutrition_ingredients__ingredient_id__nutrition_get: {
        parameters: {
            query: {
                qty: number;
                unit: string;
                user_id?: string | null;
            };
            header?: never;
            path: {
                ingredient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTotals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipes_recipes_get: {
        parameters: {
            query?: {
                tag?: string | null;
                region?: string | null;
                fasting_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recipe_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_recipe_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_route_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_nutrition_recipes__recipe_id__nutrition_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                servings?: number;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionTotals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_chai_beverages_build_chai_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChaiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_coffee_beverages_build_coffee_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoffeeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_lassi_beverages_build_lassi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LassiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_buttermilk_beverages_build_buttermilk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ButtermilkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_nimbu_paani_beverages_build_nimbu_paani_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NimbuPaaniRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_juice_beverages_build_juice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JuiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_alcohol_beverages_build_alcohol_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlcoholRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_protein_shake_beverages_build_protein_shake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProteinShakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_profile__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_route_profile__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_profile_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_profile__user_id__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRecommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_units_units__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["HouseholdUnit"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_unit_units__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrateUnitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdUnit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_entry_logs__user_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_logs__user_id__day__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLog"] | components["schemas"]["QuarantinedLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_day_tag_logs__user_id__day__date__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logged_dates_logs__user_id__dates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_logs__user_id__range__start___end__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                start: string;
                end: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["MealLog"] | components["schemas"]["QuarantinedLog"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_week_logs__user_id__week__week_ending__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                week_ending: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_logs__user_id__entries__log_id___index__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                log_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLog"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_insights__user_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
